import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/lib/database';
import {initial,type State} from '@/lib/campaign';
import {env} from 'cloudflare:workers';
export class AppError extends Error{constructor(message:string,public status=400){super(message)}}
export async function context(){const user=await getChatGPTUser();if(!user)throw new AppError('Entre com sua conta para acessar a campanha.',401);const db=database();let row=await db.prepare('SELECT data, revision FROM campaign WHERE id = ?').bind('main').first<{data:string;revision:number}>();if(!row){throw new AppError('A campanha ainda precisa ser ativada pelo gestor.',428);}const state=JSON.parse(row.data) as State;const admin=state.admin===user.userId;const person=state.people.find(p=>p.email&&p.email===user.email.toLowerCase());if(!admin&&!person)throw new AppError('Seu e-mail ainda não foi vinculado à campanha. Solicite o cadastro ao gestor.',403);return {user,db,state,revision:row.revision,admin,person};}
export function checkOrigin(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)throw new AppError('Origem inválida.',403)}
export function responseError(e:unknown){if(e instanceof AppError)return Response.json({error:e.message},{status:e.status});console.error(e);return Response.json({error:'Não foi possível concluir. Seus dados não foram descartados; tente novamente.'},{status:503});}
export async function save(c:Awaited<ReturnType<typeof context>>,action:string){c.state.audit.push({at:new Date().toISOString(),actor:c.user.email,action});const r=await c.db.prepare('UPDATE campaign SET data = ?, revision = revision + 1 WHERE id = ? AND revision = ?').bind(JSON.stringify(c.state),'main',c.revision).run();if(!r.meta.changes)throw new AppError('Outra alteração ocorreu. Atualize a página antes de tentar novamente.',409);}
function participantEmails(){const raw=(env as unknown as {PARTICIPANT_EMAILS?:string}).PARTICIPANT_EMAILS;if(!raw)return [];try{const value=JSON.parse(raw);return Array.isArray(value)?value.filter(v=>typeof v==='string'):[]}catch{return []}}
export async function bootstrap(req:Request){checkOrigin(req);const u=await getChatGPTUser();if(!u)throw new AppError('Entre com sua conta.',401);const db=database();await db.prepare('INSERT INTO campaign (id,revision,data) VALUES (?,0,?) ON CONFLICT(id) DO NOTHING').bind('main',JSON.stringify(initial(u.userId,participantEmails()))).run();}
