import {context,checkOrigin,responseError,save,AppError,bootstrap} from '@/lib/server';
import {MONTHS,days,today,score} from '@/lib/campaign';
export const dynamic='force-dynamic';
export async function GET(){try{const c=await context();const people=c.admin?c.state.people:c.state.people.filter(p=>p.id===c.person!.id);const state={...c.state,admin:undefined,people:people.map(p=>({...p,email:c.admin?p.email:''})),tasks:c.admin?c.state.tasks:c.state.tasks.filter(t=>t.person===c.person!.id),audit:c.admin?c.state.audit.slice(-100):[]};return Response.json({state,admin:c.admin,email:c.user.email,revision:c.revision,scores:Object.fromEntries(MONTHS.map(m=>[m,Object.fromEntries(people.map(p=>[p.id,score(c.state,p,m)]))]))},{headers:{'Cache-Control':'no-store'}});}catch(e){return responseError(e)}}
function text(v:unknown,max=500){if(typeof v!=='string'||v.length>max)throw new AppError('Texto inválido.');return v.trim()}
export async function POST(req:Request){try{checkOrigin(req);const b=await req.json() as Record<string,any>;if(!b||typeof b!=='object'||Array.isArray(b))throw new AppError('Requisição inválida.');if(b.action==='activate'){await bootstrap(req);return Response.json({ok:true});}const c=await context();if(b.revision!==c.revision)throw new AppError('Os dados foram alterados. Atualize antes de salvar.',409);const s=c.state;const month=String(b.month);if(!MONTHS.includes(month))throw new AppError('Mês inválido.');const m=s.months[month];if(m.closed)throw new AppError('Este mês já foi fechado.');if(b.action!=='submit'&&!c.admin)throw new AppError('Ação exclusiva do gestor.',403);
if(b.action==='person'){const p=s.people.find(p=>p.id===b.id);if(!p)throw new AppError('Pessoa inválida.');const email=text(b.email,200).toLowerCase();if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new AppError('Informe um e-mail válido.');if(email&&s.people.some(v=>v.id!==p.id&&v.email===email))throw new AppError('E-mail já utilizado por outra pessoa.');const sector=text(b.sector,100);if(s.tasks.some(t=>t.person===p.id&&t.submittedAt)&&p.sector!==sector)throw new AppError('O setor fica fixo após a primeira entrega.');p.email=email;p.sector=sector;}
else if(b.action==='metrics'){const sector=text(b.sector,100);if(!sector||!s.people.some(p=>p.sector===sector))throw new AppError('Configure primeiro os setores dos participantes.');const target=Number(b.target),revenue=Number(b.revenue);if(!Number.isFinite(target)||target<=0||!Number.isFinite(revenue)||revenue<0||target>1e12||revenue>1e12)throw new AppError('Informe meta positiva e faturamento não negativo.');m.sectors[sector]={target,revenue};}
else if(b.action==='calendar'){if(today()>=month+'-01'||s.tasks.some(t=>t.date.startsWith(month)))throw new AppError('Defina o calendário antes do início do mês e antes de cadastrar desafios.');if(!Array.isArray(b.excluded)||b.excluded.some((v:unknown)=>typeof v!=='string'||!days(month).includes(v)))throw new AppError('Informe datas úteis válidas deste mês.');m.excluded=[...new Set(b.excluded)] as string[];if(!days(month,m.excluded).length)throw new AppError('O mês precisa ter ao menos um dia útil.');}
else if(b.action==='create'){const date=text(b.date,10);if(!days(month,m.excluded).includes(date)||date<today())throw new AppError('Escolha um dia útil atual ou futuro deste mês.');const ids=b.person==='all'?s.people.map(p=>p.id):[b.person];if(ids.some((id:string)=>!s.people.some(p=>p.id===id)))throw new AppError('Pessoa inválida.');if(s.tasks.some(t=>t.date===date&&ids.includes(t.person)&&t.submittedAt))throw new AppError('Os desafios de um dia ficam fixos após a primeira entrega.');const title=text(b.title,150),description=text(b.description,2000);if(!title)throw new AppError('Informe o desafio.');for(const person of ids)s.tasks.push({id:crypto.randomUUID(),person,date,title,description,status:'open',comment:'',review:''});}
else if(b.action==='submit'){const t=s.tasks.find(t=>t.id===b.id&&t.date.startsWith(month));if(!t||!c.person||t.person!==c.person.id)throw new AppError('Você só pode enviar seus próprios desafios.',403);if(t.date!==today())throw new AppError('As entregas são permitidas apenas no dia do desafio, até 23h59 de Brasília.');if(!['open','rejected'].includes(t.status))throw new AppError('Esta entrega já foi enviada.');const evidence=await c.db.prepare('SELECT id FROM evidence WHERE task = ? LIMIT 1').bind(t.id).first();if(!evidence)throw new AppError('Anexe um comprovante antes de enviar.');t.comment=text(b.comment,2000);t.status='pending';t.submittedAt=new Date().toISOString();}
else if(b.action==='review'){const t=s.tasks.find(t=>t.id===b.id&&t.date.startsWith(month));if(!t||!['approved','rejected','waived'].includes(b.status))throw new AppError('Validação inválida.');if(b.status!=='waived'&&t.status!=='pending')throw new AppError('Só é possível validar uma entrega pendente.');const reason=text(b.reason,1000);if(b.status!=='approved'&&!reason)throw new AppError('Informe a justificativa.');t.status=b.status;t.review=reason;}
else if(b.action==='close'){if(today()<=days(month).slice(-1)[0])throw new AppError('O fechamento só fica disponível após o último dia útil do mês.');if(s.tasks.some(t=>t.date.startsWith(month)&&t.status==='pending'))throw new AppError('Valide todas as entregas pendentes antes de fechar.');if(s.people.some(p=>!p.sector||!m.sectors[p.sector]?.target))throw new AppError('Configure as metas de todos os setores antes de fechar.');m.closed={at:new Date().toISOString(),scores:Object.fromEntries(s.people.map(p=>[p.id,score(s,p,month)]))};}
else throw new AppError('Ação inválida.');await save(c,`${b.action} · ${month}${b.id?' · '+b.id:''}${b.reason?' · '+b.reason:''}`);return Response.json({ok:true});}catch(e){return responseError(e)}}

